### ISSUE TITLE
I can't merge...

### ISSUE THREAD

**Issue by nicker7** [Gouvernathor/renpy-TranslationTools#1]
I can't merge for lack of an example of how to pass the parameter

after putting the `sort_translates_ren.py` in the game folder and opening the terminal and running the command `translation_tools.sort_translates()`

symbol appears greater than

as if waiting for me to pass a parameter

but when passing the name of the folder appears this here

syntax error next to unexpected token `portuguese`

**Comment by Gouvernathor** [comment]
Calling the function should be enough to edit the existing translation files, provided you did generate them before calling the function, as said in the Readme. If you don't see anything new appearing in the console - or as you say, the `>` awaiting the next command - it means that it didn't encounter any problem and probably worked as intended.

In python, passing a parameter (here, the name of the language) means writing it inside the parentheses of the function. So, for example, `translation_tools.sort_translates("portuguese")`. But if you already generated the portugues translation files it shouldn't be necessary to do that.

**Comment by nicker7** [comment]
I deleted the folder and did the test with the command `translation_tools.sort_translates("portuguese")`

but it still continued to give the same error as always

desktop:~/Programas/renpy-8.0.2-sdk/Jogos/Confined_with_goddesses-0.2.9-dists/Confined_with_goddesses-0.2.9-pc/game$ translation_tools.sort_translates("portuguese")
bash: erro de sintaxe próximo ao token inesperado `"portuguese"'

Does this tool have a specific version of Ren'Py, in order to work?

so I can try to compile the game on it to try to use the tool

**Comment by Gouvernathor** [comment]
What the hell are you doing writing python in a bash console ? It's written in the readme to call the function in the renpy console within your game, which is enabled with Shift+O.
You don't need a particular version of renpy and you don't need to compile the game for it to work, just launch it from the launcher.

**Comment by nicker7** [comment]
I'm sorry, I thought I was supposed to send these commands in the terminal, but apparently the renpy console doesn't open with the Shift + O command in linux.

But now i got it, now i just have to figure out how to open the game console through linux.
